name: environment input test

on:
  workflow_dispatch:
    inputs:
      environment:
          type: environment
          default: prod

jobs:
  show-input:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: show variable
        run: |
          echo ${{ env.NAME }}
