name: environment input test

on:
  workflow_dispatch:
    inputs:
      environment:
          type: environment
          default: prod

env:
 APP_NAME: ${{ vars.NAME }}

jobs:
  show-input:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: show variable
        run: |
          echo ${APP_NAME}
