name: DeployGate

on:
  workflow_dispatch:
    inputs:
      build_variants:
        type: choice
        description: 'Build Variants'
        required: false
        default: 'debug'
        options:
          - 'debug'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: inputs check
        run: echo "build_variants=${{ inputs.build_variants }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build App Bundle
        run: ./gradlew assembleDebug

      - name: Distribute App
        run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
            -v "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
